USB_VID = 0xCAFE
USB_PID = 0xBABE
USB_PRODUCT = "carlossless usbkb"
USB_MANUFACTURER = "carlossless"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_ESP_PSRAM_SIZE = 2MB
CIRCUITPY_ESP_PSRAM_MODE = qio
CIRCUITPY_ESP_PSRAM_FREQ = 80m

# screen too small for the display
CIRCUITPY_TERMINALIO = 0
# still load the fontio module
CIRCUITPY_FONTIO = 1
